In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Load Data
df=pd.read_csv("nassau_candy.csv")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [3]:
# Shape
print("Row:",df.shape[0])
print("Columns:",df.shape[1])

Row: 10194
Columns: 18

In [4]:
# Information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  str
 2   Order Date      10194 non-null  str
 3   Ship Date       10194 non-null  str
 4   Ship Mode       10194 non-null  str
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  str
 7   City            10194 non-null  str
 8   State/Province  10194 non-null  str
 9   Postal Code     10194 non-null  str
 10  Division        10194 non-null  str
 11  Region          10194 non-null  str
 12  Product ID      10194 non-null  str
 13  Product Name    10194 non-null  str
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: float64(3), int64(3), str(12)
memory usage: 2.9 MB

In [5]:
# Missing Values
missing=df.isnull().sum()
missing[missing>0]

Series([], dtype: int64)

In [6]:
# Duplicate rows
print("Duplicate rows:",df.duplicated().sum())

Duplicate rows: 0

In [7]:
# Unique Values
print("Unique Order IDs:",df["Order ID"].nunique())
print("Unique Products:",df["Product Name"].nunique())
print("Unique States:",df["State/Province"].nunique())
print("Unique Citites:",df["City"].nunique())
print("Unique Customers:",df["Customer ID"].nunique())

Unique Order IDs: 8549
Unique Products: 15
Unique States: 59
Unique Citites: 542
Unique Customers: 5044

In [8]:
# Date Inspection
df["Order Date"]=pd.to_datetime(df["Order Date"], dayfirst=True, errors="coerce")
df["Ship Date"]=pd.to_datetime(df["Ship Date"], dayfirst=True, errors="coerce")

print("Order Date Range:")
print(df["Order Date"].min(),"to",df["Order Date"].max())

print("\nShip Date Range:")
print(df["Ship Date"].min(),"to",df["Ship Date"].max())

Order Date Range:
2024-01-02 00:00:00 to 2025-12-31 00:00:00

Ship Date Range:
2026-06-30 00:00:00 to 2030-06-28 00:00:00

In [9]:
# Numerical Summary
df[["Sales","Units","Gross Profit","Cost"]].describe()

              Sales         Units  Gross Profit          Cost
count  10194.000000  10194.000000  10194.000000  10194.000000
mean      13.908537      3.791838      9.166451      4.742087
std       11.341020      2.228317      6.643740      5.061647
min        1.250000      1.000000      0.250000      0.600000
25%        7.200000      2.000000      4.900000      2.400000
50%       10.800000      3.000000      7.470000      3.600000
75%       18.000000      5.000000     12.250000      5.700000
max      260.000000     14.000000    130.000000    130.000000

In [14]:
# Business Totals
print("Total Sales:",df["Sales"].sum())
print("Total Units:",df["Units"].sum())
print("Total Gross Profit:",df["Gross Profit"].sum())
print("Total Cost:",df["Cost"].sum())

Total Sales: 141783.63
Total Units: 38654
Total Gross Profit: 93442.79999999999
Total Cost: 48340.83

In [16]:
# Profit Validation
profit_difference=(df["Sales"]-df["Cost"]-df["Gross Profit"])
print("Profit mismatches:",(profit_difference.abs()>1e-9).sum())

Profit mismatches: 0

In [18]:
# Initial Python Business Profiling
ship_mode_summary=(df.groupby("Ship Mode").agg(Shipments=("Order ID","count"),Sales=("Sales","sum"),Units=("Units","sum"),Gross_Profits=("Gross Profit","sum")).sort_values("Shipments",ascending=False))
ship_mode_summary

                Shipments     Sales  Units  Gross_Profits
Ship Mode
Standard Class       6120  85490.35  23409       56424.46
Second Class         1979  27860.22   7546       18306.52
First Class          1548  21319.39   5724       14011.09
Same Day              547   7113.67   1975        4700.73

In [19]:
region_summary=(df.groupby("Region").agg(Shipments=("Order ID","count"),Sales=("Sales","sum"),Units=("Units","sum"),Gross_Profits=("Gross Profit","sum")).sort_values("Shipments",ascending=False))
region_summary

          Shipments     Sales  Units  Gross_Profits
Region
Pacific        3253  46301.53  12466       30485.94
Atlantic       2986  41197.24  11159       26973.70
Interior       2335  32037.60   8820       21282.49
Gulf           1620  22247.26   6209       14700.67

In [20]:
# Lead-Time KPIs
lead_time=(df["Ship Date"]-df["Order Date"]).dt.days
lead_time.describe()

count    10194.000000
mean      1320.841868
std        262.444892
min        904.000000
25%       1271.000000
50%       1274.000000
75%       1638.000000
max       1642.000000
dtype: float64